// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    "intro",

    "getting-started",

    "authentication",

    "quick-start",

    {
      type: "category",
      label: "Orders",
      items: [
        "orders/create-order",
        "orders/bulk-order",
        "orders/delivery-status",
        "orders/current-balance",
      ],
    },

    {
      type: "category",
      label: "API Reference",
      items: [
        {
          type: "autogenerated",
          dirName: "api",
        },
      ],
    },

    {
      type: "category",
      label: "Changelog",
      items: [
        "changelog/index",
        "changelog/v1.2.0",
        "changelog/v1.1.0",
        "changelog/v1.0.0",
      ],
    },

    {
      type: "category",
      label: "Payments",
      items: [
        "payments/get-payments",
        "payments/get-payment-details",
        "payments/mermaid",
      ],
    },

  ],
};

export default sidebars;
