// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    'getting-started',
    'authentication',
    'quick-start',

    {
      type: "category",
      label: 'Orders',
      items: ['orders/create-order'],
    },

    {
      type: "category",
      label: 'API Reference',
      items: [
        {
          type: "autogenerated",
          dirName: 'api',
        },
      ],
    },

    {
      type: "category",
      label: 'Changelog',
      items: [
        'changelog/index',
        'changelog/v1.2.0',
        'changelog/v1.1.0',
        'changelog/v1.0.0',
      ],
    },

    {
      type: "category",
      label: 'Payments',
      items: ['payments/mermaid'],
    },
  ],
};

export default sidebars;
